/**
 * React version of DraftOle MVP Demo
 *
 * DraftOle examples/interactive/mvp-demo.ts の React (SSG) 版等価実装。
 * 比較検討用。React + react-dom/server で静的HTML を生成する。
 *
 * 実行方法:
 *   pnpm add -D react react-dom @types/react @types/react-dom
 *   pnpm tsx examples/interactive/react-demo.tsx
 *
 * 出力先:
 *   .out/runs/react_demo/index.html
 */

// ────────────────────────────────────────────────────────────
// Section 1: Import & 定数定義
// ────────────────────────────────────────────────────────────

import { renderToStaticMarkup } from 'react-dom/server';
import { writeFileSync, mkdirSync } from 'node:fs';

const OUTPUT_DIR = '.out/runs/react_demo';

// ────────────────────────────────────────────────────────────
// Section 2: HTML構造の構築（JSXコンポーネント）
// ────────────────────────────────────────────────────────────

function App() {
  return (
    <html lang="ja">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>React MVP Demo</title>
      </head>
      <body>
        <main id="app" className="app">
          <header className="header">
            <h1 className="title">React MVP Demo</h1>
            <p className="subtitle">JSXで型安全なHTML生成</p>
          </header>
          {/* 入力フォーム（空 - タスク3.3 相当） */}
          <section className="card" />
          {/* Todoリスト（空 - タスク3.3 相当） */}
          <section className="card" />
          <footer className="footer">
            <small>Generated by React (sample output)</small>
          </footer>
        </main>
      </body>
    </html>
  );
}

// ────────────────────────────────────────────────────────────
// Section 3: CSS定義
// ────────────────────────────────────────────────────────────

// React単体ではCSS統合機能を持たないため、以下のいずれかを別途採用する必要がある:
//   - CSS Modules（ビルドツール要）
//   - styled-components / Emotion（ランタイム依存）
//   - Tailwind CSS（ユーティリティクラス）
//   - 外部 .css ファイルを手書きで用意
//
// DraftOle は .css.padding() のように HTML と同じ API で CSS を書ける点が差別化要素。

// ────────────────────────────────────────────────────────────
// Section 4: JS定義
// ────────────────────────────────────────────────────────────

// React SSG の出力は静的HTMLのみ。クライアントサイドの動的処理が必要な場合は:
//   - 別途クライアント用 JS をバンドルして <script> で読み込む
//   - または hydrateRoot() でインタラクティブ化（この場合 react ランタイムが必要）
//
// DraftOle は JQueryManager で生成した JS を同じビルド成果物として出力できる。

// ────────────────────────────────────────────────────────────
// Section 5: ファイル出力
// ────────────────────────────────────────────────────────────

const htmlContent = `<!doctype html>\n${renderToStaticMarkup(<App />)}`;

mkdirSync(OUTPUT_DIR, { recursive: true });
writeFileSync(`${OUTPUT_DIR}/index.html`, htmlContent);

console.log('React MVP Demo - 完了');
console.log(`出力先: ${OUTPUT_DIR}`);

// ────────────────────────────────────────────────────────────
// 比較メモ: DraftOle vs React (SSG)
// ────────────────────────────────────────────────────────────
//
// | 観点           | DraftOle                         | React (SSG)                       |
// |----------------|----------------------------------|-----------------------------------|
// | ビルド         | tsx 直接実行可                   | JSX変換が必要（tsx/bun/esbuild）  |
// | 依存           | ゼロ（純TS）                     | react + react-dom (~140KB dev)    |
// | 構文           | div({class:'x'}, child)          | <div className="x">child</div>    |
// | 属性名         | HTML準拠 (class, for, charset)   | React独自 (className, htmlFor…)   |
// | CSS統合        | ✓（同じAPIで .css.padding(…)）   | ✗（別途ソリューション必須）       |
// | JS統合         | ✓（JQueryManager）               | ✗（クライアントJSは別バンドル）   |
// | コンポーネント | 関数でラップ（DF-8）             | function Component() ネイティブ   |
// | 型安全         | ✓                                | ✓                                 |
// | エコシステム   | なし                             | 最大（shadcn/ui等）               |
