/**
 * Task 6.2: MVP Demo出力検証テスト
 *
 * mvp-demoが生成したHTML/CSS/JSファイルの内容を検証する。
 * output/mvp_demo/ の既存出力ファイルを読み取り、
 * 構造・スタイル・ロジックが期待通りであることを確認する。
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const OUTPUT_DIR = join(process.cwd(), 'output', 'mvp_demo');

describe('Task 6.2: MVP Demo Output', () => {
  const html = readFileSync(join(OUTPUT_DIR, 'index.html'), 'utf-8');
  const css = readFileSync(join(OUTPUT_DIR, 'style.css'), 'utf-8');
  const js = readFileSync(join(OUTPUT_DIR, 'script.js'), 'utf-8');

  describe('HTML structure', () => {
    it('contains app container', () => {
      expect(html).toContain('id="app"');
    });

    it('contains header with title', () => {
      expect(html).toContain('DraftOle MVP Demo');
    });

    it('contains todo input', () => {
      expect(html).toContain('id="todo-input"');
    });

    it('contains add button', () => {
      expect(html).toContain('id="add-btn"');
    });

    it('contains todo list', () => {
      expect(html).toContain('id="todo-list"');
    });

    it('contains clear button', () => {
      expect(html).toContain('id="clear-btn"');
    });

    it('contains footer', () => {
      expect(html).toContain('Generated by DraftOle');
    });

    it('contains link to stylesheet', () => {
      expect(html).toContain('href="style.css"');
    });

    it('contains script tag', () => {
      expect(html).toContain('src="script.js"');
    });
  });

  describe('CSS content', () => {
    it('contains CSS variables', () => {
      expect(css).toContain('--bg:');
    });

    it('contains card styles', () => {
      expect(css).toContain('.card');
    });

    it('contains button styles', () => {
      expect(css).toContain('.btn');
    });

    it('contains list styles', () => {
      expect(css).toContain('.list');
    });

    it('contains item styles', () => {
      expect(css).toContain('.item');
    });

    it('contains pill styles', () => {
      expect(css).toContain('.pill');
    });
  });

  describe('JavaScript content', () => {
    it('contains createTodoItem function', () => {
      expect(js).toContain('function createTodoItem');
    });

    it('contains addTodo function', () => {
      expect(js).toContain('function addTodo');
    });

    it('contains updateCount function', () => {
      expect(js).toContain('function updateCount');
    });

    it('contains clearDone function', () => {
      expect(js).toContain('function clearDone');
    });

    it('contains DOMContentLoaded handler', () => {
      expect(js).toContain('DOMContentLoaded');
    });
  });
});
