/**
 * DraftOle MVP Demo: Todo App
 *
 * DraftOle の SwiftUI ライク API で Todo アプリを生成する。
 * CSS変数・疑似セレクタ等はDraftOle未サポートのため、
 * 補完CSSとして手動追加する。
 *
 * 実行: node --experimental-strip-types examples/mvp-demo.ts
 * 出力: output/mvp_demo/index.html, style.css, script.js
 */
import {
  Root, Text,
  html, head, body, title, meta,
  div, h1, p, section, header, footer,
  form, label, input, button, ul, span, small,
  FileExporter,
} from '../dist/index.js';

// ── Document ──
const root = new Root();

const page = html({ lang: 'ja' },
  head(
    meta({ charset: 'utf-8' }),
    meta({ name: 'viewport', content: 'width=device-width, initial-scale=1' }),
    title('DraftOle MVP Demo'),
  ),
  body(
    div({ id: 'app', class: 'app' },
      // ── Header ──
      header({ class: 'header' },
        h1('DraftOle MVP Demo').margin('0').fontSize('28px'),
        p('TypeScript DSLから生成されたHTML/CSS/JS（サーバ不要）')
          .margin('8px 0 0').color('rgba(255,255,255,0.68)'),
      ),

      // ── Input Card ──
      section({ class: 'card' },
        div({ class: 'row' },
          label({ for: 'todo-input', class: 'label' }, 'Todo'),
          input({ id: 'todo-input', class: 'input', type: 'text', placeholder: '例: DraftOleのCSS出力を確認する' }),
          button({ id: 'add-btn', class: 'btn primary', type: 'button' }, '追加'),
        ),
        div({ class: 'row meta' },
          span({ id: 'count', class: 'count' }, '0 items'),
          button({ id: 'clear-btn', class: 'btn', type: 'button' }, '完了をクリア'),
        ),
      ),

      // ── Todo List Card ──
      section({ class: 'card' },
        ul({ id: 'todo-list', class: 'list', 'aria-label': 'Todo list' }),
      ),

      // ── Footer ──
      footer({ class: 'footer' },
        small('Generated by DraftOle'),
      ).margin('18px 0 0'),
    ).maxWidth('860px').margin('0 auto').padding('36px 18px 60px'),
  ),
);

root.addChild(page);

// ── JS: Todo アプリロジック ──
// DraftOle の JQueryManager ではカバーできないロジックを直接記述
const appJs = `// Todo App Logic
function createTodoItem(text) {
  const li = document.createElement("li");
  li.className = "item";

  const span = document.createElement("span");
  span.className = "text";
  span.textContent = text;

  const pill = document.createElement("span");
  pill.className = "pill ng";
  pill.textContent = "active";

  const btn = document.createElement("button");
  btn.className = "btn";
  btn.type = "button";
  btn.textContent = "toggle";

  btn.addEventListener("click", () => {
    li.classList.toggle("done");
    const done = li.classList.contains("done");
    pill.textContent = done ? "done" : "active";
    pill.classList.toggle("ok", done);
    pill.classList.toggle("ng", !done);
    updateCount();
  });

  li.appendChild(span);
  li.appendChild(pill);
  li.appendChild(btn);
  return li;
}

function updateCount() {
  const items = document.querySelectorAll("#todo-list .item");
  const active = Array.from(items).filter(x => !x.classList.contains("done")).length;
  document.querySelector("#count").textContent = active + " items";
}

function clearDone() {
  document.querySelectorAll("#todo-list .item.done").forEach(el => el.remove());
  updateCount();
}

function addTodo() {
  const input = document.querySelector("#todo-input");
  const text = (input.value || "").trim();
  if (!text) {
    input.style.borderColor = "rgba(239, 68, 68, 0.65)";
    return;
  }
  input.style.borderColor = "rgba(255, 255, 255, 0.12)";
  document.querySelector("#todo-list").appendChild(createTodoItem(text));
  input.value = "";
  updateCount();
}

document.addEventListener("DOMContentLoaded", () => {
  document.querySelector("#add-btn").addEventListener("click", addTodo);
  document.querySelector("#clear-btn").addEventListener("click", clearDone);
  document.querySelector("#todo-input").addEventListener("keydown", e => {
    if (e.key === "Enter") addTodo();
  });
  updateCount();
});`;

// ── CSS: DraftOle 未サポート機能を補完 ──
// CSS変数、疑似セレクタ、複合セレクタ、radial-gradient 等
const supplementCss = `/* CSS Variables */
:root {
  --bg: #0b1220;
  --panel: rgba(255, 255, 255, 0.06);
  --border: rgba(255, 255, 255, 0.12);
  --text: rgba(255, 255, 255, 0.92);
  --muted: rgba(255, 255, 255, 0.68);
  --accent: #7c5cff;
  --accent-2: #32d399;
  --danger: #ef4444;
  --shadow: 0 18px 60px rgba(0, 0, 0, 0.35);
  --radius: 14px;
}

* { box-sizing: border-box; }
html, body { height: 100%; }

body {
  font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, "Apple Color Emoji", "Segoe UI Emoji";
  background: radial-gradient(1200px 600px at 20% 10%, rgba(124, 92, 255, 0.35), transparent 60%),
              radial-gradient(900px 500px at 80% 20%, rgba(50, 211, 153, 0.25), transparent 60%),
              var(--bg);
  color: var(--text);
  margin: 0;
}

/* Card */
.card {
  background: var(--panel);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  box-shadow: var(--shadow);
  padding: 16px;
  margin-top: 14px;
}

/* Row layout */
.row { display: flex; gap: 10px; align-items: center; flex-wrap: wrap; }
.row.meta { margin-top: 12px; justify-content: space-between; }

/* Label */
.label { min-width: 44px; color: var(--muted); }

/* Input */
.input {
  flex: 1 1 260px;
  padding: 11px 12px;
  border-radius: 12px;
  border: 1px solid var(--border);
  background: rgba(0, 0, 0, 0.25);
  color: var(--text);
  outline: none;
}
.input:focus {
  border-color: rgba(124, 92, 255, 0.65);
  box-shadow: 0 0 0 3px rgba(124, 92, 255, 0.25);
}

/* Button */
.btn {
  padding: 10px 12px;
  border-radius: 12px;
  border: 1px solid var(--border);
  background: rgba(255, 255, 255, 0.06);
  color: var(--text);
  cursor: pointer;
}
.btn:hover { background: rgba(255, 255, 255, 0.10); }
.btn.primary {
  border-color: rgba(124, 92, 255, 0.55);
  background: linear-gradient(180deg, rgba(124, 92, 255, 0.35), rgba(124, 92, 255, 0.18));
}

/* Count */
.count { color: var(--muted); }

/* Todo List */
.list { list-style: none; padding: 0; margin: 0; display: grid; gap: 10px; }

/* Todo Item */
.item {
  display: flex; align-items: center; justify-content: space-between;
  gap: 10px; padding: 12px; border-radius: 12px;
  border: 1px solid var(--border); background: rgba(0, 0, 0, 0.22);
}
.item .text { flex: 1 1 auto; }
.item.done .text { text-decoration: line-through; color: rgba(255, 255, 255, 0.55); }

/* Pill */
.pill {
  display: inline-flex; align-items: center; gap: 6px;
  border-radius: 999px; padding: 6px 10px;
  border: 1px solid var(--border); background: rgba(255, 255, 255, 0.05);
  color: var(--muted); font-size: 12px;
}
.pill.ok { color: rgba(50, 211, 153, 0.95); border-color: rgba(50, 211, 153, 0.35); }
.pill.ng { color: rgba(239, 68, 68, 0.95); border-color: rgba(239, 68, 68, 0.35); }

/* Footer */
.footer { color: var(--muted); }`;

// ── Export ──
const htmlContent = root.render();
const scopedCss = root.collectCssStyleString();
const cssContent = supplementCss + (scopedCss ? '\n\n/* Scoped CSS */\n' + scopedCss : '');
const jsContent = appJs;

const exporter = new FileExporter();
exporter.export(htmlContent, cssContent, jsContent, './output/mvp_demo');

console.log('✓ MVP Demo generated → output/mvp_demo/');
