/**
 * build-runtime.ts
 *
 * DraftOle ランタイムプレリュードのビルドパイプライン（Req 5.6）
 *
 * パイプライン:
 *   src/runtime/prelude.ts
 *     → tsc -p src/runtime/tsconfig.json  (ES2019, module: none)
 *     → esbuild --bundle --format=iife
 *     → src/js/vanilla/internal/runtime-prelude.gen.ts として文字列エクスポート
 *
 * 実行方法:
 *   node --experimental-strip-types scripts/build-runtime.ts
 *   npm run build:runtime
 */

import { execFileSync } from "node:child_process";
import * as fs from "node:fs";
import { createRequire } from "node:module";
import * as path from "node:path";

// ---------------------------------------------------------------------------
// パス設定
// ---------------------------------------------------------------------------

const PROJECT_ROOT = new URL("..", import.meta.url).pathname;

const RUNTIME_TSCONFIG = path.join(PROJECT_ROOT, "src/runtime/tsconfig.json");
const TSC_OUT_DIR = path.join(PROJECT_ROOT, "dist/runtime");
const TSC_OUT_FILE = path.join(TSC_OUT_DIR, "prelude.js");
const GEN_OUT_FILE = path.join(
  PROJECT_ROOT,
  "src/js/vanilla/internal/runtime-prelude.gen.ts"
);

// ---------------------------------------------------------------------------
// esbuild ロード（pnpm 環境では createRequire 経由で解決）
// ---------------------------------------------------------------------------

// pnpm では esbuild は .pnpm 内の仮想ストアにあるため、
// esbuild パッケージ自身の package.json を起点に require する
const ESBUILD_PKG = path.join(
  PROJECT_ROOT,
  "node_modules/.pnpm/esbuild@0.27.2/node_modules/esbuild/package.json"
);
const requireFromEsbuild = createRequire(ESBUILD_PKG);
const esbuild = requireFromEsbuild("esbuild") as typeof import("esbuild");

// ---------------------------------------------------------------------------
// Step 1: tsc でコンパイル（ES2019, module: none）
// ---------------------------------------------------------------------------

console.log("[build-runtime] Step 1: tsc -p src/runtime/tsconfig.json");

// dist/runtime ディレクトリが存在しない場合に備えて作成
fs.mkdirSync(TSC_OUT_DIR, { recursive: true });

execFileSync(
  "node",
  [path.join(PROJECT_ROOT, "node_modules/typescript/bin/tsc"), "-p", RUNTIME_TSCONFIG],
  {
    cwd: PROJECT_ROOT,
    stdio: "inherit",
  }
);

if (!fs.existsSync(TSC_OUT_FILE)) {
  throw new Error(`[build-runtime] tsc output not found: ${TSC_OUT_FILE}`);
}

console.log("[build-runtime] tsc complete:", TSC_OUT_FILE);

// ---------------------------------------------------------------------------
// Step 2: esbuild で IIFE バンドル
// ---------------------------------------------------------------------------

console.log("[build-runtime] Step 2: esbuild --format=iife");

const result = await esbuild.build({
  entryPoints: [TSC_OUT_FILE],
  bundle: false,
  format: "iife",
  minify: false,
  write: false,
  target: "es2019",
});

if (result.outputFiles === undefined || result.outputFiles.length === 0) {
  throw new Error("[build-runtime] esbuild produced no output");
}

const iifeCode = result.outputFiles[0].text.trim();

console.log("[build-runtime] esbuild complete, output size:", iifeCode.length, "bytes");

// ---------------------------------------------------------------------------
// Step 3: .gen.ts として文字列エクスポート
// ---------------------------------------------------------------------------

console.log("[build-runtime] Step 3: writing", GEN_OUT_FILE);

const genContent = `// AUTO-GENERATED by scripts/build-runtime.ts — DO NOT EDIT
export const RUNTIME_PRELUDE = \`${iifeCode.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${")}\`;
`;

fs.mkdirSync(path.dirname(GEN_OUT_FILE), { recursive: true });
fs.writeFileSync(GEN_OUT_FILE, genContent, "utf-8");

console.log("[build-runtime] Done:", GEN_OUT_FILE);
