// AUTO-GENERATED by scripts/build-runtime.ts — DO NOT EDIT
export const RUNTIME_PRELUDE = `"use strict";
(() => {
  (function() {
    const states = /* @__PURE__ */ new Map();
    let pending = /* @__PURE__ */ new Set();
    let isFlushing = false;
    let isInternalPropagation = false;
    function getEntry(id) {
      const entry = states.get(id);
      if (entry === void 0) {
        throw new Error("unknown state: " + id);
      }
      return entry;
    }
    function flush() {
      if (isFlushing) {
        return;
      }
      isFlushing = true;
      try {
        while (pending.size > 0) {
          const ids = pending;
          pending = /* @__PURE__ */ new Set();
          ids.forEach(function(id) {
            const entry = states.get(id);
            if (entry === void 0)
              return;
            const value = entry.value;
            entry.subs.forEach(function(sub) {
              try {
                sub(value);
              } catch (err) {
                console.error("[DraftOle] subscriber error for state '" + id + "':", err);
              }
            });
          });
        }
      } finally {
        isFlushing = false;
      }
    }
    function setState(id, v) {
      const entry = getEntry(id);
      if (entry.value === v)
        return;
      entry.value = v;
      pending.add(id);
      if (!isFlushing) {
        queueMicrotask(flush);
      } else if (!isInternalPropagation) {
        console.warn("[DraftOle] state '" + id + "' was set during flush; will be processed in next batch.");
      }
      if (entry.parent !== void 0) {
        propagateToParent(entry.parent, v);
      }
    }
    function propagateToParent(meta, newSlotValue) {
      const parentEntry = states.get(meta.id);
      if (parentEntry === void 0) {
        console.warn("[DraftOle] propagateToParent: parent state '" + meta.id + "' not found; skipping propagation.");
        return;
      }
      const parentValue = parentEntry.value;
      if (!Array.isArray(parentValue)) {
        console.warn("[DraftOle] propagateToParent: parent state '" + meta.id + "' is not an array; skipping propagation.");
        return;
      }
      if (meta.index < 0 || meta.index >= parentValue.length) {
        console.warn("[DraftOle] propagateToParent: index " + String(meta.index) + " out of range for parent state '" + meta.id + "' (length=" + String(parentValue.length) + "); skipping propagation.");
        return;
      }
      const newArr = parentValue.slice();
      newArr[meta.index] = newSlotValue;
      const prev = isInternalPropagation;
      isInternalPropagation = true;
      try {
        setState(meta.id, newArr);
      } finally {
        isInternalPropagation = prev;
      }
    }
    function itemStateId(parentId, idx) {
      return parentId + ".item" + String(idx);
    }
    function ensureItemState(parentId, idx, value) {
      const id = itemStateId(parentId, idx);
      if (!states.has(id)) {
        states.set(id, {
          value,
          subs: /* @__PURE__ */ new Set(),
          parent: { id: parentId, index: idx }
        });
      } else {
        const entry = states.get(id);
        if (entry.value !== value) {
          entry.value = value;
          pending.add(id);
          if (!isFlushing) {
            queueMicrotask(flush);
          }
        }
      }
      return id;
    }
    const runtime = {
      /**
       * 状態を初期化（state-init コマンドから呼ばれる）（Req 1.2）。
       * 既登録の場合は無視（二重初期化防止）。
       */
      initState(id, initial) {
        if (!states.has(id)) {
          states.set(id, { value: initial, subs: /* @__PURE__ */ new Set() });
        }
      },
      /**
       * 状態ハンドルを取得。
       * 未登録 ID に対しては Error をスロー（Req エラーハンドリング）。
       */
      state(id) {
        getEntry(id);
        return {
          get() {
            return getEntry(id).value;
          },
          set(v) {
            setState(id, v);
          },
          subscribe(fn) {
            const entry = getEntry(id);
            const sub = fn;
            entry.subs.add(sub);
            try {
              fn(entry.value);
            } catch (err) {
              console.error("[DraftOle] subscriber error (initial) for state '" + id + "':", err);
            }
            return function() {
              const e = states.get(id);
              if (e !== void 0) {
                e.subs.delete(sub);
              }
            };
          }
        };
      },
      /**
       * textContent バインディング（Req 4.1）。
       * transform が指定された場合は状態値を変換して適用する。
       */
      bindText(el, stateId, transform) {
        runtime.state(stateId).subscribe(function(v) {
          const text = transform !== void 0 ? transform(v) : String(v);
          el.textContent = text;
        });
      },
      /**
       * input.value バインディング（Req 4.2）。
       */
      bindValue(el, stateId, transform) {
        runtime.state(stateId).subscribe(function(v) {
          el.value = transform !== void 0 ? String(transform(v)) : String(v);
        });
      },
      /**
       * className 全置換バインディング（Req 4.5）。
       */
      bindClassAll(el, stateId, transform) {
        runtime.state(stateId).subscribe(function(v) {
          const cls = transform !== void 0 ? transform(v) : String(v);
          el.className = cls;
        });
      },
      /**
       * クラス追加（差分）バインディング（Req 4.3）。
       * 旧クラス削除 → 新クラス付与 の差分操作（Req 4.3 AC 3）。
       */
      bindClassAdd(el, stateId, transform) {
        let prevClass = "";
        runtime.state(stateId).subscribe(function(v) {
          const newClass = transform !== void 0 ? transform(v) : String(v);
          if (prevClass !== "" && prevClass !== newClass) {
            el.classList.remove(prevClass);
          }
          if (newClass !== "" && newClass !== prevClass) {
            el.classList.add(newClass);
          }
          prevClass = newClass;
        });
      },
      /**
       * style プロパティバインディング（Req 4.4）。
       */
      bindStyle(el, prop, stateId, transform) {
        runtime.state(stateId).subscribe(function(v) {
          const val = transform !== void 0 ? transform(v) : String(v);
          el.style.setProperty(prop, val);
        });
      },
      /**
       * checked バインディング（input[type=checkbox] 等）。
       */
      bindChecked(el, stateId, transform) {
        runtime.state(stateId).subscribe(function(v) {
          el.checked = transform !== void 0 ? Boolean(transform(v)) : Boolean(v);
        });
      },
      /**
       * 配列差分描画バインディング（Req 3.6）。
       *
       * アルゴリズム（Req 3.6 AC 6, Design R-5, R-6）:
       *   1. 配列長増加 → factory で DOM 要素追加
       *   2. 配列長減少 → lastChild を removeChild
       *   3. 各スロット State を "{stateId}.item{i}" で仮想 State として更新
       */
      bindEach(parent, stateId, factory) {
        runtime.state(stateId).subscribe(function(arr) {
          for (let i = 0; i < arr.length; i++) {
            ensureItemState(stateId, i, arr[i]);
          }
          while (parent.children.length < arr.length) {
            const idx = parent.children.length;
            const itemId = ensureItemState(stateId, idx, arr[idx]);
            const childEl = factory(itemId, idx);
            parent.appendChild(childEl);
          }
          while (parent.children.length > arr.length) {
            const last = parent.lastChild;
            if (last !== null) {
              parent.removeChild(last);
            }
          }
          for (let i = 0; i < arr.length; i++) {
            const itemId = itemStateId(stateId, i);
            const entry = states.get(itemId);
            if (entry !== void 0 && entry.value !== arr[i]) {
              entry.value = arr[i];
              pending.add(itemId);
            }
          }
          if (pending.size > 0 && !isFlushing) {
            queueMicrotask(flush);
          }
        });
      }
    };
    window["__draftole__"] = runtime;
  })();
})();`;
